<a href="https://colab.research.google.com/github/5Spaak/5Spaak/blob/main/Tutoriel_Complet_de_Numpy_avec_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy - Numerical Python**

**Avantages de Tableau Numpy**


1.   Permet plusieurs opérations mathématiques
2.   Opérations plus rapides



In [3]:
# importer la bibliothèque
import numpy as np

List vs Numpy - Time Taken

In [4]:
from time import process_time

Time taken by list

In [5]:
python_list = [i for i in range(1000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.00025051699999956156


Time taken by Numpy

In [6]:
np_array = np.array([i for i in range(1000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time - start_time)

0.0012622239999995344


In [7]:
# List
list1 =[1,2,3,4,5,6]
print(list1)

[1, 2, 3, 4, 5, 6]


In [8]:
type(list1)

list

In [9]:
# Numpy Arrays
np_array = np.array([1,2,3,4,5])

In [10]:
print(np_array)

[1 2 3 4 5]


In [11]:
type(np_array)

numpy.ndarray

In [12]:
# create a 1 dim array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [13]:
a.shape

(5,)

In [14]:
# Numpy array with Mutiple Dimensions
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
b.shape

(2, 4)

In [16]:
c = np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [17]:
# Create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
# Create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [27]:
# array of a particular value
z = np.full((5,4),4)
print(z)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [30]:
# Create an identity matrix
a = np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [34]:
# Create a numpy with random value
b = np.random.random((3,4))
print(b)

[[0.46179021 0.6723951  0.04767685 0.58826825]
 [0.49347656 0.79071503 0.21257544 0.14673493]
 [0.51209694 0.09961929 0.65138989 0.03013606]]


In [38]:
# random integer values with a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[43 82 17 76 26]
 [40 70 57 93 79]
 [46 49 51 30 93]]


In [49]:
# array of evenly spaced values (specifying the number of values required)
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [51]:
# array of evenly spaced values (specifying the step)
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [52]:
# convert a list to a numpy
list2 = [10,20,30,50,60]
np_array = np.asarray(list2)
print(np_array)

[10 20 30 50 60]


In [53]:
type(np_array)

numpy.ndarray

Analysing a numpy array

In [54]:
# analysing a numpy array
c = np.random.randint(10,90,(5,5))
print(c)

[[21 84 60 38 16]
 [36 26 38 67 35]
 [63 52 27 45 43]
 [38 20 24 25 14]
 [88 11 28 56 26]]


In [55]:
# array dimension
print(c.shape)

(5, 5)


In [56]:
# number of dimensions
print(c.ndim)

2


In [57]:
# number of elements in an array
print(c.size)

25


In [58]:
# checking the data type of the values in the array
print(c.dtype)

int64


In [60]:
# Mathematical Operation on a np array
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2) # concatenate or join

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [61]:
# Using np array
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [62]:
print(a)
print(b)

[[5 4 0]
 [4 9 7]
 [9 7 9]]
[[12 14 10]
 [18 19 18]
 [13 14 14]]


In [63]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 18 10]
 [22 28 25]
 [22 21 23]]
[[ -7 -10 -10]
 [-14 -10 -11]
 [ -4  -7  -5]]
[[ 60  56   0]
 [ 72 171 126]
 [117  98 126]]
[[0.41666667 0.28571429 0.        ]
 [0.22222222 0.47368421 0.38888889]
 [0.69230769 0.5        0.64285714]]


In [64]:
# Using np array
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [65]:
print(a)
print(b)

[[1 5 1]
 [3 0 3]
 [3 4 0]]
[[14 11 19]
 [12 11 15]
 [11 16 14]]


In [66]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 16 20]
 [15 11 18]
 [14 20 14]]
[[-13  -6 -18]
 [ -9 -11 -12]
 [ -8 -12 -14]]
[[14 55 19]
 [36  0 45]
 [33 64  0]]
[[0.07142857 0.45454545 0.05263158]
 [0.25       0.         0.2       ]
 [0.27272727 0.25       0.        ]]


In [67]:
# Array Manipulation
array = np.random.randint(0,10,(2,3))
print(array)

[[2 4 2]
 [9 6 3]]


In [68]:
print(array.shape)

(2, 3)


In [69]:
# Transpose
trans = np.transpose(array)
print(trans)

[[2 9]
 [4 6]
 [2 3]]


In [70]:
array = np.random.randint(0,10,(2,3))
print(array)

[[3 8 7]
 [4 2 4]]


In [71]:
print(array.shape)

(2, 3)


In [72]:
# Transposition 2
trans2 = array.T
print(trans2)

[[3 4]
 [8 2]
 [7 4]]


In [73]:
# reshaping a array
a = np.random.randint(0,10,(3,4))
print(a)

[[5 7 9 4]
 [7 7 1 0]
 [3 2 5 5]]


In [74]:
print(a.shape)

(3, 4)


In [75]:
b = a.reshape(4,3)
print(b)

[[5 7 9]
 [4 7 7]
 [1 0 3]
 [2 5 5]]


In [76]:
print(b.shape)

(4, 3)
